const smoothies20 = [
    {
        id: 1,
        flavor: "Almond Joy",
        size: 20,
        calories: 302,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 2,
        flavor: "Apple Pie",
        size: 20,
        calories: 409,
        total_fat: 2.5,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 60,
        dietary_fiber: 3.5,
        sugars: 31.5,
        protein: 36.5
    },
    {
        id: 3,
        flavor: "Banana Cream Pie",
        size: 20,
        calories: 395,
        total_fat: 2.5,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 54.5,
        dietary_fiber: 4.5,
        sugars: 24.5,
        protein: 38.5
    },
    {
        id: 4,
        flavor: "Banana Nut Muffin",
        size: 20,
        calories: 391,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 55.5,
        dietary_fiber: 3.5,
        sugars: 21,
        protein: 40
    },
    {
        id: 5,
        flavor: "Blonde Mocha",
        size: 20,
        calories: 309,
        total_fat: 6.5,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 21.5,
        total_carbohydrates: 17,
        dietary_fiber: 2.5,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 6,
        flavor: "Blueberry Cobbler",
        size: 20,
        calories: 336,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 21.5,
        total_carbohydrates: 25,
        dietary_fiber: 4.5,
        sugars: 9,
        protein: 45.5
    },
    {
        id: 7,
        flavor: "Chocolate Banana Bomber",
        size: 20,
        calories: 364,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 8,
        flavor: "Chocolate Covered Strawberry",
        size: 20,
        calories: 328,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 23,
        dietary_fiber: 4,
        sugars: 7.5,
        protein: 45.5
    },
    {
        id: 9,
        flavor: "Chocolate Irish Cream",
        size: 20,
        calories: 302,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 10,
        flavor: "Chocolate Irish Mocha",
        size: 20,
        calories: 302,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 11,
        flavor: "Chocolate Peanut Butter Blast",
        size: 20,
        calories: 354,
        total_fat: 10,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 18,
        dietary_fiber: 3.5,
        sugars: 3.5,
        protein: 48
    },
    {
        id: 12,
        flavor: "Cinnamon Mocha Fudge",
        size: 20,
        calories: 302,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 13,
        flavor: "Cinnamon Roll",
        size: 20,
        calories: 271,
        total_fat: 2.5,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 24.5,
        dietary_fiber: 1.5,
        sugars: 5.5,
        protein: 37.5
    },
    {
        id: 14,
        flavor: "Coco Mocha Fudge",
        size: 20,
        calories: 305,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 15,
        flavor: "Coconut Cream Pie",
        size: 20,
        calories: 271,
        total_fat: 2.5,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 24.5,
        dietary_fiber: 1.5,
        sugars: 5.5,
        protein: 37.5
    },
    {
        id: 16,
        flavor: "Cookies n Cream",
        size: 20,
        calories: 359,
        total_fat: 5,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 6.5,
        total_carbohydrates: 24.5,
        dietary_fiber: 1,
        sugars: 10,
        protein: 54
    },
    {
        id: 33,
        flavor: "Do-Si-Do",
        size: 20,
        calories: 354,
        total_fat: 10,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 18,
        dietary_fiber: 3.5,
        sugars: 3.5,
        protein: 48
    },
    {
        id: 17,
        flavor: "Fudge Brownie",
        size: 20,
        calories: 302,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 18,
        flavor: "Fudge Mocha",
        size: 20,
        calories: 302,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 19,
        flavor: "Lemon Meringue Pie",
        size: 20,
        calories: 318,
        total_fat: 2,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 6.5,
        total_carbohydrates: 20.5,
        dietary_fiber: 1.5,
        sugars: 5,
        protein: 54.5
    },
    {
        id: 20,
        flavor: "Mocha Almond Fudge",
        size: 20,
        calories: 302,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 21,
        flavor: "Neopolitan",
        size: 20,
        calories: 330,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 21.5,
        total_carbohydrates: 23.5,
        dietary_fiber: 3.5,
        sugars: 7.5,
        protein: 45.5
    },
    {
        id: 22,
        flavor: "Peaches & Cream",
        size: 20,
        calories: 251,
        total_fat: 0.5,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 6.5,
        total_carbohydrates: 8,
        dietary_fiber: 0.5,
        sugars: 1,
        protein: 53.5
    },
    {
        id: 23,
        flavor: "Pina Colada",
        size: 20,
        calories: 253,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 27.6,
        dietary_fiber: 0.5,
        sugars: 15.5,
        protein: 33.5
    },
    {
        id: 24,
        flavor: "Pineapple Passion",
        size: 20,
        calories: 253,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 27.5,
        dietary_fiber: 0.5,
        sugars: 15.5,
        protein: 33.5
    },
    {
        id: 25,
        flavor: "Pineapple Strawberry",
        size: 20,
        calories: 279,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 34,
        dietary_fiber: 1.5,
        sugars: 20,
        protein: 33.5
    },
    {
        id: 34,
        flavor: "Samoa",
        size: 20,
        calories: 247,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 16,
        dietary_fiber: 1,
        sugars: 2,
        protein: 43.5
    },
    {
        id: 35,
        flavor: "Savanna Smiles",
        size: 20,
        calories: 318,
        total_fat: 2,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 6.5,
        total_carbohydrates: 20.5,
        dietary_fiber: 1.5,
        sugars: 5,
        protein: 54.5
    },
    {
        id: 26,
        flavor: "S'mores",
        size: 20,
        calories: 367,
        total_fat: 7,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 21.5,
        total_carbohydrates: 29.5,
        dietary_fiber: 3.5,
        sugars: 7,
        protein: 46.5
    },
    {
        id: 27,
        flavor: "Strawberry Banana",
        size: 20,
        calories: 291,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 33.5,
        dietary_fiber: 3,
        sugars: 15.5,
        protein: 37
    },
    {
        id: 28,
        flavor: "Strawberry Colada",
        size: 20,
        calories: 279,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 34,
        dietary_fiber: 1.5,
        sugars: 20,
        protein: 33.5
    },
    {
        id: 29,
        flavor: "Strawberry D-Light",
        size: 20,
        calories: 255,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 25,
        dietary_fiber: 2.5,
        sugars: 10.5,
        protein: 36.5
    },
    {
        id: 35,
        flavor: "Tag-a-Long",
        size: 20,
        calories: 354,
        total_fat: 10,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 18,
        dietary_fiber: 3.5,
        sugars: 3.5,
        protein: 48
    },
    {
        id: 36,
        flavor: "Thin Mint",
        size: 20,
        calories: 302,
        total_fat: 6,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 23,
        total_carbohydrates: 16.5,
        dietary_fiber: 3,
        sugars: 3,
        protein: 45.5
    },
    {
        id: 30,
        flavor: "Tropical",
        size: 20,
        calories: 315,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 9.5,
        total_carbohydrates: 42.6,
        dietary_fiber: 2,
        sugars: 25,
        protein: 34
    },
    {
        id: 31,
        flavor: "Vanilla",
        size: 20,
        calories: 247,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 16,
        dietary_fiber: 1,
        sugars: 2,
        protein: 43.5
    },
    {
        id: 32,
        flavor: "Wedding Cake",
        size: 20,
        calories: 247,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 16,
        dietary_fiber: 1,
        sugars: 2,
        protein: 43.5
    },
]

export default smoothies20;