const smoothies32 = [
    {
        id: 1,
        flavor: "Almond Joy",
        size: 32,
        calories: 442,
        total_fat: 8,
        saturated_fat: 8,
        trans_fat: 2,
        cholesterol: 31,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        sugars: 4,
        protein: 68.5
    },
    {
        id: 2,
        flavor: "Apple Pie",
        size: 32,
        calories: 593,
        total_fat: 2.5,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 84.5,
        dietary_fiber: 4,
        sugars: 39.5,
        protein: 58
    },
    {
        id: 3,
        flavor: "Banana Cream Pie",
        size: 32,
        calories: 567,
        total_fat: 3,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 79.5,
        dietary_fiber: 7,
        sugars: 36.5,
        protein: 55.5
    },
    {
        id: 4,
        flavor: "Banana Nut Muffin",
        size: 32,
        calories: 597,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 88,
        dietary_fiber: 5.5,
        sugars: 31.5,
        protein: 59
    },
    {
        id: 5,
        flavor: "Blonde Mocha",
        size: 32,
        calories: 437,
        total_fat: 7,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 28,
        total_carbohydrates: 25,
        dietary_fiber: 3,
        sugars: 4,
        protein: 68.5
    },
    {
        id: 6,
        flavor: "Blueberry Cobbler",
        size: 32,
        calories: 501,
        total_fat: 7,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 28,
        total_carbohydrates: 41,
        dietary_fiber: 7,
        sugars: 16,
        protein: 68.5
    },
    {
        id: 7,
        flavor: "Chocolate Banana Bomber",
        size: 32,
        calories: 566,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 54,
        dietary_fiber: 7,
        sugars: 23,
        protein: 69.5
    },
    {
        id: 8,
        flavor: "Chocolate Covered Strawberry",
        size: 32,
        calories: 494,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 37,
        dietary_fiber: 6,
        sugars: 13,
        protein: 68.5
    },
    {
        id: 9,
        flavor: "Chocolate Irish Cream",
        size: 32,
        calories: 442,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 24,
        dietary_fiber: 7,
        sugars: 4,
        protein: 68.5
    },
    {
        id: 10,
        flavor: "Chocolate Irish Mocha",
        size: 32,
        calories: 442,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        sugars: 4,
        protein: 68.5
    },
    {
        id: 11,
        flavor: "Chocolate Peanut Butter Blast",
        size: 32,
        calories: 553,
        total_fat: 15,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 27,
        dietary_fiber: 5,
        sugars: 5,
        protein: 72.5
    },
    {
        id: 12,
        flavor: "Cinnamon Mocha Fudge",
        size: 32,
        calories: 442,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        sugars: 4,
        protein: 68.5
    },
    {
        id: 13,
        flavor: "Cinnamon Roll",
        size: 32,
        calories: 381,
        total_fat: 3,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 34.5,
        dietary_fiber: 2.5,
        sugars: 8,
        protein: 54
    },
    {
        id: 14,
        flavor: "Coco Mocha Fudge",
        size: 32,
        calories: 442,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        sugars: 4,
        protein: 68.5
    },
    {
        id: 15,
        flavor: "Coconut Cream Pie",
        size: 32,
        calories: 381,
        total_fat: 3,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 34.5,
        dietary_fiber: 2.5,
        sugars: 8,
        protein: 54
    },
    {
        id: 16,
        flavor: "Cookies n Cream",
        size: 32,
        calories: 538,
        total_fat: 7.5,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 40.5,
        dietary_fiber: 1.5,
        sugars: 15.5,
        protein: 77
    },
    {
        id: 17,
        flavor: "Fudge Brownie",
        size: 32,
        calories: 442,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        sugars: 4,
        protein: 68.5
    },
    {
        id: 18,
        flavor: "Fudge Mocha",
        size: 32,
        calories: 442,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        sugars: 4,
        protein: 68.5
    },
    {
        id: 19,
        flavor: "Lemon Meringue Pie",
        size: 32,
        calories: 477,
        total_fat: 3,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 34.5,
        dietary_fiber: 2.5,
        sugars: 8,
        protein: 78
    },
    {
        id: 20,
        flavor: "Mocha Almond Fudge",
        size: 32,
        calories: 442,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 31,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        sugars: 4,
        protein: 68.5
    },
    {
        id: 21,
        flavor: "Neopolitan",
        size: 32,
        calories: 489,
        total_fat: 7,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 28,
        total_carbohydrates: 38,
        dietary_fiber: 5,
        sugars: 13,
        protein: 68.5
    },
    {
        id: 22,
        flavor: "Peaches & Cream",
        size: 32,
        calories: 375,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 15,
        dietary_fiber: 1,
        sugars: 2,
        protein: 76.5
    },
    {
        id: 23,
        flavor: "Pina Colada",
        size: 32,
        calories: 365,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 36.5,
        dietary_fiber: 1,
        sugars: 20.5,
        protein: 52.5
    },
    {
        id: 24,
        flavor: "Pineapple Passion",
        size: 32,
        calories: 365,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 36.5,
        dietary_fiber: 1,
        sugars: 20.5,
        protein: 52.5
    },
    {
        id: 25,
        flavor: "Pineapple Strawberry",
        size: 32,
        calories: 417,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 49.5,
        dietary_fiber: 3,
        sugars: 29.5,
        protein: 52.5
    },
    {
        id: 26,
        flavor: "Smores",
        size: 32,
        calories: 535,
        total_fat: 9,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 28,
        total_carbohydrates: 43.5,
        dietary_fiber: 4.5,
        sugars: 10,
        protein: 70
    },
    {
        id: 27,
        flavor: "Strawberry Banana",
        size: 32,
        calories: 459,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 59,
        dietary_fiber: 6,
        sugars: 30,
        protein: 53.5
    },
    {
        id: 28,
        flavor: "Strawberry Colada",
        size: 32,
        calories: 417,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 49.5,
        dietary_fiber: 3,
        sugars: 29.5,
        protein: 52.5
    },
    {
        id: 29,
        flavor: "Strawberry D-Light",
        size: 32,
        calories: 361,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 36.5,
        dietary_fiber: 4,
        sugars: 15.5,
        protein: 52.5
    },
    {
        id: 30,
        flavor: "Tropical",
        size: 32,
        calories: 489,
        total_fat: 1,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 13,
        total_carbohydrates: 66.5,
        dietary_fiber: 4,
        sugars: 39.5,
        protein: 53.5
    },
    {
        id: 31,
        flavor: "Vanilla",
        size: 32,
        calories: 376,
        total_fat: 1.5,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 19.5,
        total_carbohydrates: 24,
        dietary_fiber: 1.5,
        sugars: 3,
        protein: 66.5
    },
    {
        id: 32,
        flavor: "Wedding Cake",
        size: 32,
        calories: 376,
        total_fat: 1.5,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 19.5,
        total_carbohydrates: 24,
        dietary_fiber: 1.5,
        sugars: 23,
        protein: 66.5
    },
]

export default smoothies32;